apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
        - name: fastapi-container
          image: <your_ecr_repo>/fastapi-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: APP_MODE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: API_KEY
